export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const RETRIEVE_LOGGEDIN_USER = "RETRIEVE_LOGGEDIN_USER";
export const CREATE_USER = "UPDATE_USER";
export const UPDATE_USER = "CREATE_USER";
export const DELETE_USER = "DELETE USER";
export const RESTORE_USER = "RESTORE_USER";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
export const VERIFY_TAX_INFO = "VERIFY_TAX_INFO";

export const RETRIEVE_COUNTRIES = "RETRIEVE_COUNTRIES";
export const RETRIEVE_STATES = "RETRIEVE_STATES";
export const RETRIEVE_CITIES = "RETRIEVE_CITIES";

export const RETRIEVE_SPACES = "RETRIEVE_SPACES";
export const UPDATE_SPACE_STATUS = "UPDATE_SPACE_STATUS";
export const UPDATE_IS_ACTIVE = "UPDATE_IS_ACTIVE";
export const DELETE_SPACE = "DELETE_SPACE";
export const RESTORE_SPACE = "RESTORE_SPACE";

export const SHOW_IMAGE_BACKDROP = "SHOW_IMAGE_BACKDROP";
export const CLOSE_IMAGE_BACKDROP = "CLOSE_IMAGE_BACKDROP";
export const SHOW_VIDEO_BACKDROP = "SHOW_VIDEO_BACKDROP";
export const CLOSE_VIDEO_BACKDROP = "CLOSE_VIDEO_BACKDROP";

export const RETRIEVE_PAGES = "RETRIEVE_PAGES";
export const CREATE_PAGE = "CREATE_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const RESTORE_PAGE = "RESTORE_PAGE";
export const UPDATE_PAGE_STATUS = "UPDATE_PAGE_STATUS";

export const RETRIEVE_STORAGE_TYPES = "RETRIEVE_STORAGE_TYPES";
export const CREATE_STORAGE_TYPE = "CREATE_STORAGE_TYPE";
export const UPDATE_STORAGE_TYPE = "UPDATE_STORAGE_TYPE";
export const DELETE_STORAGE_TYPE = "DELETE_STORAGE_TYPE";
export const RESTORE_STORAGE_TYPE = "RESTORE_STORAGE_TYPE";
export const UPDATE_STORAGE_TYPE_STATUS = "UPDATE_STORAGE_TYPE_STATUS";

export const RETRIEVE_SOURCES = "RETRIEVE_SOURCES";
export const CREATE_SOURCE = "CREATE_SOURCE";
export const UPDATE_SOURCE = "UPDATE_SOURCE";
export const DELETE_SOURCE = "DELETE_SOURCE";

export const RETRIEVE_REVIEWS = "RETRIEVE_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const RESTORE_REVIEW = "RESTORE_REVIEW";
export const UPDATE_REVIEW_STATUS = "UPDATE_REVIEW_STATUS";

export const RETRIEVE_RESERVATIONS = "RETRIEVE_RESERVATIONS";
export const UPDATE_RESERVATION_STATUS = "UPDATE_RESERVATION_STATUS";
export const UPDATE_PAYOUT_HOLD_STATUS = "UPDATE_PAYOUT_HOLD_STATUS";

export const RETRIEVE_TRANSACTIONS = "RETRIEVE_TRANSACTIONS";
export const RETRIEVE_RENTER_TRANSACTIONS = "RETRIEVE_RENTER_TRANSACTIONS";
export const REFUND_AMOUNT = "REFUND AMOUNT";

export const RETRIEVE_REFUNDS = "RETRIEVE_REFUNDS";

export const RETRIEVE_PAYOUTS = "RETRIEVE_PAYOUTS";
export const RETRIEVE_HOST_PAYOUTS = "RETRIEVE_HOST_PAYOUTS";

export const RETRIEVE_FAQ = "RETRIEVE_FAQ";
export const CREATE_FAQ = "CREATE_FAQ";
export const UPDATE_FAQ = "UPDATE_FAQ";
export const DELETE_FAQ = "DELETE_FAQ";
export const RESTORE_FAQ = "RESTORE_FAQ";
export const UPDATE_FAQ_STATUS = "UPDATE_FAQ_STATUS";

export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

export const UPDATE_BECOME_A_HOST = "UPDATE_BECOME_A_HOST";
